---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: restcall-operator
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./config/default
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: restcall-operator
  targetNamespace: default
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: restcall-sample
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/managed-by: RestcallController
              app.kubernetes.io/name: restcall-operator
              app.kubernetes.io/version: 0.0.5
          template:
            spec:
              containers:
                - env:
                  - name: REST_URL
                    value: o2ims-infrastructureInventory/v1
                  name: rest
                      
      target:
        name: restcall-sample
        kind: Deployment
